id: os_sshd_key_exchange_algorithm_configure
title: "Configure SSHD to Use Secure Key Exchange Algorithms"
discussion: |
  Unapproved mechanisms for authentication to the cryptographic module are not verified, and therefore cannot be relied upon to provide confidentiality or integrity, resulting in the compromise of DoD data.

  Operating systems using encryption are required to use FIPS-compliant mechanisms for authenticating to cryptographic modules.

  The implementation of OpenSSH that is included with macOS does not utilize a FIPS 140-2 validated cryptographic module. While the listed Key Exchange Algorithms are FIPS 140-2 approved, the module implementing them has not been validated.

  By specifying a Key Exchange Algorithm list with the order of hashes being in a "strongest to weakest" orientation, the system will automatically attempt to use the strongest Key Exchange Algorithm for securing SSH connections.

  NOTE: /etc/ssh/sshd_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/sbin/sshd -T | /usr/bin/grep -ci "^KexAlgorithms diffie-hellman-group-exchange-sha256"
result:
  integer: 1
fix: |
  [source,bash]
  ----
  include_dir=$(/usr/bin/awk '/^Include/ {print $2}' /etc/ssh/sshd_config | /usr/bin/tr -d '*')

  if [[ -z $include_dir ]]; then
    /usr/bin/sed -i.bk "1s/.*/Include \/etc\/ssh\/sshd_config.d\/\*/" /etc/ssh/sshd_config
  fi

  echo "KexAlgorithms diffie-hellman-group-exchange-sha256" >> "${include_dir}01-mscp-sshd.conf"

  for file in $(ls ${include_dir}); do
    if [[ "$file" == "100-macos.conf" ]]; then
        continue
    fi
    if [[ "$file" == "01-mscp-sshd.conf" ]]; then
        break
    fi
    /bin/mv ${include_dir}${file} ${include_dir}20-${file}
  done
  ----  
references:
  cce:
    - CCE-91891-2
  cci: 
    - CCI-000803
    - CCI-000068
    - CCI-000087
    - CCI-003123
    - CCI-002890
  800-53r5:
    - AC-17(2)
    - IA-7
    - MA-4(6)
  800-53r4: 
    - IA-7
    - AC-17(2)
    - MA-4(6)
  srg:
    - SRG-OS-000033-GPOS-00014
    - SRG-OS-000120-GPOS-00061
    - SRG-OS-000125-GPOS-00065
    - SRG-OS-000250-GPOS-00093
    - SRG-OS-000393-GPOS-00173
    - SRG-OS-000394-GPOS-00174
  disa_stig:
    - APPL-12-000056
  800-171r2:
    - N/A
  cmmc:
    - AC.L2-3.1.13
macOS:
  - "13.0"
tags:
  - stig
  - cmmc_lvl2
  - cmmc_lvl3
severity: "medium"
mobileconfig: false
mobileconfig_info: